server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #cloud.config.server.native.search-locations ：本地配置⽂件存放的路径
          search-locations: classpath:/shared