server:
  port: 7090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        #设置开启请求跟踪
        enabled: true
    #设置采样⽐例，默认是 1.0
    sampler:
      probability: 1.0
  zipkin:
    #Zipkin Server 地址
    base-url: http://localhost:9999/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/